# Generated by Django 4.0.4 on 2022-04-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_url',
        ),
    ]
